.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    critic.model.enable_gradient_checkpointing=True \
    critic.optim.lr=1e-5 \
    critic.model.enable_gradient_checkpointing=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.logger=['wandb'] \
    +trainer.val_before_train=False \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=2 \
    trainer.nnodes=1 \
    trainer.save_freq=100 \
    trainer.test_freq=500 \
    trainer.project_name=pubmed_search \
    trainer.experiment_name=pubmed_search_32_continuing3250 \
    actor_rollout_ref.model.path=checkpoints/pubmed_search/pubmed_search_32_continuing2500/actor/global_step_750 \
    critic.model.path=checkpoints/pubmed_search/pubmed_search_32_continuing2500/critic/global_step_750 \
    trainer.total_epochs=10 2>&1 | tee exp_log/32-ppo-verl_demo_$DATE.log