#export NCCL_DEBUG=INFO
#export NCCL_SOCKET_IFNAME=^lo,docker0  # 排除 loopback 和 docker 网络
#export OMP_NUM_THREADS=4
#export MASTER_ADDR=10.11.50.32   # 注意：仍然是 gpu008 的 IP
#export MASTER_PORT=29500
#export NODE_RANK=1               # 当前是 rank 1 节点
export CUDA_VISIBLE_DEVICES=0,1

DATE=$(date '+%Y-%m-%d-%H-%M-%S')
#torchrun \
#  --nnodes=2 \
#  --nproc_per_node=8 \
#  --node_rank=$NODE_RANK \
#  --master_addr=$MASTER_ADDR \
#  --master_port=$MASTER_PORT \
python3  -m verl.trainer.main_ppo \
    data.train_files=data/search_engine/pubmed_32/train.parquet \
    data.val_files=data/search_engine/pubmed_32/test.parquet \
    data.train_batch_size=16 \
    data.val_batch_size=16 \
    data.max_prompt_length=500 \
    data.max_response_length=500 \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.strategy=fsdp \
    actor_rollout_ref.actor.ppo_mini_batch_size=16 \
    actor_rollout_ref.actor.ppo_micro_batch_size=8 \
    critic.ppo_micro_batch_size=8 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=2 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=2 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    critic.model.enable_gradient_checkpointing=True \
    critic.optim.lr=1e-5 \
    critic.model.enable_gradient_checkpointing=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.logger=['wandb'] \
    +trainer.val_before_train=False \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=2 \
    trainer.nnodes=1 \
    trainer.save_freq=50 \
    trainer.test_freq=500 \
    trainer.project_name=pubmed_search \
    trainer.experiment_name=pubmed_search_32_7B \
    actor_rollout_ref.model.path=/data/vayu/train/models/xDAN-L1-Qwen25-7B-Instruct \
    critic.model.path=/data/vayu/train/models/xDAN-L1-Qwen25-7B-Instruct \
    trainer.total_epochs=10 2>&1 | tee exp_log/32-ppo-verl_demo_$DATE.log 